name:  module_toolkit
description: Stuff to help think of widgets as mock modules
dependencies:
  models:
    path: ../models
  widgets:
    path: ../widgets
  flutter:
    sdk: flutter
dev_dependencies:
  test: any
