# Copyright 2016 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: widgets
description: UI widgets for FX
dependencies:
  intl: ^0.14.0
  email_session_store:
    path: ../email_session_store
  flutter:
    sdk: flutter
  models:
    path: ../models
  xml: ^2.4.3
dependency_overrides:
  http:
    path: ../../packages/flutter-http/
dev_dependencies:
  test: any
  fixtures:
    path: ../fixtures
  flutter_test:
    sdk: flutter
