name: widgets
description: UI widgets for FX
dependencies:
  flutter:
    path: ../../third_party/flutter/packages/flutter
  models:
    path: ../models
dev_dependencies:
  test: any
  flutter_test:
    path: ../../third_party/flutter/packages/flutter_test
