name: widgets
description: UI widgets for FX
dependencies:
  flutter:
    sdk: flutter
  models:
    path: ../models
  module_toolkit:
    path: ../module_toolkit
dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
