name: widgets
description: UI widgets for FX
dependencies:
  flutter:
    sdk: flutter
  models:
    path: ../models
  resolver:
    path: ../resolver
dev_dependencies:
  test: 0.12.15+4
  flutter_test:
    sdk: flutter
