name:  resolver
description: Find widgets to embed given a specific set of constraints.
dependencies:
  models:
    path: ../models
  widgets:
    path: ../widgets
  flutter:
    sdk: flutter
dev_dependencies:
  test: 0.12.15+4
